name = "honeytools"
license = "LGPL-3.0-or-later"
author = "Gabriele Bellomia"
maintainer = "gbellomia@live.it"
copyright = "Copyright 2022, Gabriele Bellomia"
description = "Honeycomb flakes, sheets, ribbons, whatever. Made easy."
keywords = ["tight-binding","graphene","honeycomb","flakes","ribbons","stripes","lattice"]
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = true
[dependencies]
assert.git  = "https://github.com/sourceryinstitute/assert.git"
assert.tag  = "1.4.0"
ogpf.git    = "https://github.com/bellomia/OGPF.git"
ogpf.branch = "expose-term-options-to-user" 
pyplot-fortran.git = "https://github.com/jacobwilliams/pyplot-fortran.git"
pyplot-fortran.tag = "3.2.0"
stdlib.git = "https://github.com/fortran-lang/stdlib"
stdlib.branch = "stdlib-fpm"