add_hex – HoneyTools
add_hex Function
5 statements
Source File
private pure elemental function add_hex(A, B) result(C)
Addition overload for hex type
Arguments
Type Intent Optional Attributes Name
type(hex), intent(in) :: A
type(hex), intent(in) :: B
Return Value type(hex)
Calls
Called by
Contents
None
Call graph
add_hex calls hex
hex calls new_hex_cubic, new_hex_axial
new_hex_cubic calls assert
operator(+) calls add_hex