get_flake – HoneyTools
get_flake Function
8 statements
Source File
public pure function get_flake(radius, layout) result(lattice)
Get the lattice for a hexagon-shaped flake
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: radius
type(unit_cell), intent(in) :: layout
Return Value type(xy_lattice)
Calls
Contents
Call graph
get_flake calls hex2lattice, hex_flake
hex2lattice calls hex2corner, xy_ordered_union
hex_flake calls hex_insert
hex2corner calls hex2center, ith_corner_offset, site
xy_ordered_union calls push_back, site
hex2center calls origin, uq, ur
push_back calls site