get_stripe – HoneyTools
get_stripe Function
15 statements
Source File
public pure function get_stripe(height, width, layout) result(lattice)
Get the lattice for a hexagon-shaped flake
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: height
integer, intent(in) :: width
type(unit_cell), intent(in) :: layout
Return Value type(xy_lattice)
Calls
Contents
Call graph
get_stripe calls hex2lattice, hex_armchair_stripe, hex_zigzag_stripe
hex2lattice calls hex2corner, xy_ordered_union
hex_armchair_stripe calls hex_insert
hex_zigzag_stripe calls hex_insert
hex2corner calls hex2center, ith_corner_offset, site
xy_ordered_union calls push_back, site
hex2center calls origin, uq, ur
push_back calls site