get_triangle – HoneyTools
get_triangle Function
8 statements
Source File
public pure function get_triangle(size, layout) result(lattice)
Get the lattice for a triangle-shaped flake
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: size
type(unit_cell), intent(in) :: layout
Return Value type(xy_lattice)
Calls
Contents
Call graph
get_triangle calls hex2lattice, hex_triangle
hex2lattice calls hex2corner, xy_ordered_union
hex_triangle calls assert, hex_insert
hex2corner calls hex2center, ith_corner_offset, site
xy_ordered_union calls push_back, site
hex2center calls origin, uq, ur
push_back calls site