get_supercell – HoneyTools
get_supercell Function
8 statements
Source File
public pure function get_supercell(rows, cols, layout) result(lattice)
Get the lattice for a honeycomb supercell
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: rows
integer, intent(in) :: cols
type(unit_cell), intent(in) :: layout
Return Value type(xy_lattice)
Calls
Contents
Call graph
get_supercell calls hex2lattice, hex_supercell
hex2lattice calls hex2corner, xy_ordered_union
hex2corner calls hex2center, ith_corner_offset, site
xy_ordered_union calls push_back, site
hex2center calls origin, uq, ur
push_back calls site