hex2center – HoneyTools
hex2center Function
11 statements
Source File
public pure elemental function hex2center(layout, H) result(center)
Convert hex coordinates to real 2D space [returning the xy coordinates of the hexagon center] Actual real-space layout has to be specified by passing a (scalar) unit_cell object.
Arguments
Type Intent Optional Attributes Name
type(unit_cell), intent(in) :: layout
type(hex), intent(in) :: H
Return Value type(xy)
Calls
Called by
Contents
Call graph
hex2center calls origin, uq, ur
hex2corner calls hex2center
hex2site calls hex2center
hex2lattice calls hex2corner
hex_plot calls hex2corner, plot
plot calls hex_plot, xy_plot
get_flake calls hex2lattice
get_stripe calls hex2lattice
get_supercell calls hex2lattice
get_triangle calls hex2lattice
xy_plot calls plot