hex2lattice – HoneyTools
hex2lattice Function
16 statements
Source File
public pure function hex2lattice(layout, hexagons) result(lattice)
Generate a type(xy_lattice) object from any given hex array, provided a suitable layout (unit-cell)
Arguments
Type Intent Optional Attributes Name
type(unit_cell), intent(in) :: layout
type(hex), intent(in) :: hexagons(:)
Return Value type(xy_lattice)
Calls
Called by
Call graph
hex2lattice calls hex2corner, xy_ordered_union
hex2corner calls hex2center, ith_corner_offset
xy_ordered_union calls push_back
get_flake calls hex2lattice
get_stripe calls hex2lattice
get_supercell calls hex2lattice
get_triangle calls hex2lattice