hex2corner – HoneyTools
hex2corner Function
22 statements
Source File
public pure elemental function hex2corner(layout, H) result(corner)
Convert hex coordinates to real 2D space [returning the xy coordinates for the hexagon corners, as appropriatiely wrapped in the "xy_lattice" type] Actual real-space layout has to be specified by passing a (scalar) unit_cell object.
Arguments
Type Intent Optional Attributes Name
type(unit_cell), intent(in) :: layout
type(hex), intent(in) :: H
Return Value type(xy_lattice)
Calls
Called by
Contents
Call graph
hex2corner calls hex2center, ith_corner_offset, site
hex2center calls origin, uq, ur
hex2lattice calls hex2corner
hex_plot calls hex2corner, plot
plot calls hex_plot, xy_plot
get_flake calls hex2lattice
get_stripe calls hex2lattice
get_supercell calls hex2lattice
get_triangle calls hex2lattice
xy_plot calls plot