hex_insert – HoneyTools
hex_insert Subroutine
17 statements
Source File
public pure subroutine hex_insert(vec, val)
Utility to grow type(hex) arrays, it is a poor man implementation of a dynamic array insertion, a là std::vector (but with no preallocation and smart doubling...)
Arguments
Type Intent Optional Attributes Name
type(hex), intent(inout), allocatable :: vec(:)
type(hex), intent(in) :: val
Called by
Contents
Source Code
hex_insert
Source Code
   pure subroutine hex_insert(vec,val)
      !! Utility to grow type(hex) arrays, it is a
      !! poor man implementation of a dynamic array
      !! insertion, a là std::vector (but with no
      !! preallocation and smart doubling...)
      type(hex),intent(inout),allocatable :: vec(:)
      type(hex),intent(in)                :: val
      type(hex),allocatable               :: tmp(:)
      integer                             :: len
      if(allocated(vec))then
         len = size(vec)
         allocate(tmp(len+1))
         tmp(:len) = vec
         call move_alloc(tmp,vec)
         len = len + 1
      else
         len = 1
         allocate(vec(len))
      end if
      ! Insert val at back
      vec(len) = val
   end subroutine hex_insert
Call graph
hex_triangle calls hex_insert
hex_armchair_stripe calls hex_insert
hex_zigzag_stripe calls hex_insert
hex_flake calls hex_insert
hex_line calls hex_insert
get_triangle calls hex_triangle
get_flake calls hex_flake
get_stripe calls hex_armchair_stripe, hex_zigzag_stripe