ith_corner_offset – HoneyTools
ith_corner_offset Function
8 statements
Source File
private pure function ith_corner_offset(layout, i) result(offset)
Compute the i-th offset vector connecting the hexagon center to its corners, returning a (scalar) xy coordinate
Arguments
Type Intent Optional Attributes Name
type(unit_cell), intent(in) :: layout
integer, intent(in) :: i
Return Value type(xy)
Called by
Contents
Call graph
hex2corner calls ith_corner_offset
hex2site calls ith_corner_offset
hex2lattice calls hex2corner
hex_plot calls hex2corner, plot
plot calls hex_plot, xy_plot
get_flake calls hex2lattice
get_stripe calls hex2lattice
get_supercell calls hex2lattice
get_triangle calls hex2lattice
xy_plot calls plot