new_hex_axial – HoneyTools
new_hex_axial Function
7 statements
Source File
private pure function new_hex_axial(q, r) result(H)
Axial cubic constructor for the hex type [s would be computed internally]
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: q
integer, intent(in) :: r
Return Value type(hex)
Called by
Contents
None
Call graph
hex calls new_hex_axial
add_hex calls hex
rhs_hex calls hex
lhs_hex calls hex
sub_hex calls hex
operator(+) calls add_hex
operator(ASTERISK) calls rhs_hex, lhs_hex