push_back – HoneyTools
push_back Subroutine
18 statements
Source File
private pure subroutine push_back(vec, val)
Poor man implementation of a dynamic array, a là std::vector (but without preallocation and smart doubling...)
Type Bound
xy_lattice
Arguments
Type Intent Optional Attributes Name
class(xy_lattice), intent(inout) :: vec
type(xy_site), intent(in) :: val
Calls
Called by
Contents
Source Code
push_back
Source Code
   pure subroutine push_back(vec,val)
      !! Poor man implementation of a dynamic
      !! array, a là std::vector (but without
      !! preallocation and smart doubling...)
      class(xy_lattice),intent(inout)  :: vec
      type(xy_site),intent(in)         :: val
      type(xy_site),allocatable        :: tmp(:)
      integer                          :: len
      if (allocated(vec%site)) then
         len = size(vec%site)
         allocate(tmp(len+1))
         tmp(:len) = vec%site
         call move_alloc(tmp,vec%site)
         len = len + 1
      else
         len = 1
         allocate(vec%site(len))
      end if
      !PUSH val at the BACK
      vec%site(len) = val
      !Increade formal size
      vec%size = len
   end subroutine push_back
Call graph
push_back calls site
xy_ordered_union calls push_back
hex2lattice calls xy_ordered_union
get_flake calls hex2lattice
get_stripe calls hex2lattice
get_supercell calls hex2lattice
get_triangle calls hex2lattice