sub_hex – HoneyTools
sub_hex Function
5 statements
Source File
private pure elemental function sub_hex(A, B) result(C)
Subtraction overload for hex type
Arguments
Type Intent Optional Attributes Name
type(hex), intent(in) :: A
type(hex), intent(in) :: B
Return Value type(hex)
Calls
Called by
Contents
None
Call graph
sub_hex calls hex
hex calls new_hex_cubic, new_hex_axial
new_hex_cubic calls assert