xy_norm – HoneyTools
xy_norm Function
5 statements
Source File
private pure elemental function xy_norm(A) result(r)
polymorphic euclidean norm for xy class
Arguments
Type Intent Optional Attributes Name
class(xy), intent(in) :: A
Return Value real(kind=8)
Called by
Call graph
xy_distance calls xy_norm
xy_shells calls xy_distance
xy_nearest_neighbors calls xy_shells
xy_next_nearest_neighbors calls xy_shells