xy_next_nearest_neighbors – HoneyTools
xy_next_nearest_neighbors Subroutine
12 statements
Source File
public pure subroutine xy_next_nearest_neighbors(lattice, nnn_mask, nn_mask)
Build a mask for the next-nearest neighbors of a given lattice. It is a NxN matrix, with N the number of sites in the lattice, storing .true. values only for the pairs of sites linked by a "NNN-bond". Optionally builds a nearest-neighbors mask, too. It calls internally xy_shells, for all inter-site distances, so if you need more than NNNs consider calling xy_shells directly. Note that we provide a similar subroutine for nearest-neighbors only, so if you just need NNs consider calling it.
call xy_nearest_neighbors(lattices,nn_maks)
Arguments
Type Intent Optional Attributes Name
type(xy_lattice), intent(in) :: lattice
logical, intent(out), allocatable :: nnn_mask(:,:)
logical, intent(out), optional, allocatable :: nn_mask(:,:)
Calls
Call graph
xy_next_nearest_neighbors calls xy_shells
xy_shells calls xy_distance, sort
xy_distance calls xy_norm