hex – HoneyTools
hex Interface
4 statements
Source File
public interface hex
constructor override
Calls
Called by
Contents
Module Procedures
new_hex_cubic new_hex_axial
Module Procedures
private pure function new_hex_cubic(q, r, s) result(H)
Safe cubic constructor for the hex type featuring an assertion on input coordinates before the initialization of the object
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: q
integer, intent(in) :: r
integer, intent(in) :: s
Return Value type(hex)
private pure function new_hex_axial(q, r) result(H)
Axial cubic constructor for the hex type [s would be computed internally]
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: q
integer, intent(in) :: r
Return Value type(hex)
Call graph
hex calls new_hex_axial, new_hex_cubic
new_hex_cubic calls assert
add_hex calls hex
lhs_hex calls hex
rhs_hex calls hex
sub_hex calls hex
operator(+) calls add_hex
operator(ASTERISK) calls lhs_hex, rhs_hex