operator(*) – HoneyTools
operator(*) Interface
5 statements
Source File
public interface operator(*)
product overload
Calls
Contents
Module Procedures
rhs_hex lhs_hex dot_hex
Module Procedures
private pure elemental function rhs_hex(A, k) result(C)
Right scale overload for hex type
Arguments
Type Intent Optional Attributes Name
type(hex), intent(in) :: A
integer, intent(in) :: k
Return Value type(hex)
private pure elemental function lhs_hex(k, B) result(C)
Left scale overload for hex type
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: k
type(hex), intent(in) :: B
Return Value type(hex)
private pure elemental function dot_hex(A, B) result(C)
Dot overload for hex type
Arguments
Type Intent Optional Attributes Name
type(hex), intent(in) :: A
type(hex), intent(in) :: B
Return Value integer
Call graph
operator(ASTERISK) calls rhs_hex, lhs_hex, dot_hex
rhs_hex calls hex
lhs_hex calls hex
hex calls new_hex_cubic, new_hex_axial
new_hex_cubic calls assert