operator(+) – HoneyTools
operator(+) Interface
3 statements
Source File
public interface operator(+)
addition overload
Calls
Contents
Module Procedures
add_hex
Module Procedures
private pure elemental function add_hex(A, B) result(C)
Addition overload for hex type
Arguments
Type Intent Optional Attributes Name
type(hex), intent(in) :: A
type(hex), intent(in) :: B
Return Value type(hex)
Call graph
operator(+) calls add_hex
add_hex calls hex
hex calls new_hex_axial, new_hex_cubic
new_hex_cubic calls assert